name: main

on:
  push:
    branches:
      - master
    tags:
      - "**"
  pull_request:
    branches:
      - master

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v5
        with:
          persist-credentials: false

      - uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v4
        with:
          node-version-file: ".tool-versions"
          package-manager-cache: false

      - name: Install
        run: npm ci

      - name: Typecheck
        run: npm run typecheck

      - name: Build
        run: npm run build

      - name: Test
        run: npm run test

      - name: Format
        run: npm run fmtcheck

      - name: Check generated files
        run: |
          git diff --exit-code --stat -- . ':!node_modules' \
          || (echo "##[error] found changed files after build. please 'npm run build && npm run fmt'" \
                  "and check in all changes" \
              && exit 1)
  integration:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v5
        with:
          persist-credentials: false

      - uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v4
        with:
          node-version-file: ".tool-versions"
          package-manager-cache: false

      - name: Diffset
        id: diffset
        uses: ./ # Uses an action in the root directory
        with:
          md_files: "*.md"

      - name: Print Diffset
        env:
          DIFFSET_FILES: ${{ steps.diffset.outputs.files }}
        run: ls -al ${DIFFSET_FILES}

      - name: Print MD Files
        if: steps.diffset.outputs.md_files
        env:
          MD_FILES: ${{ steps.diffset.outputs.md_files }}
        run: echo "Files changed were ${MD_FILES}"

      - name: Print Rust Files
        if: steps.diffset.outputs.rust_files
        env:
          RUST_FILES: ${{ steps.diffset.outputs.rust_files }}
        run: echo "Files changed were ${RUST_FILES}"
